#ifndef PLAYFIELD_H
#define PLAYFIELD_H

#define PLAYFIELD_PADDLE_MARGIN 16.0f
#define PLAYFIELD_MIN_X (PADDLE_WIDTH + PLAYFIELD_PADDLE_MARGIN)
#define PLAYFIELD_MAX_X (GetScreenWidth() - (PADDLE_WIDTH + PLAYFIELD_PADDLE_MARGIN))
#define PLAYFIELD_MIN_Y 0.0f
#define PLAYFIELD_MAX_Y (GetScreenHeight())

#endif
